Milad, 5:42 PM
openapi: 3.0.1
info:
  title: iot_doc
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/User/sign-up/:
    post:
      summary: ''
      operationId: post-api-User-sign-up
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                gender:
                  type: string
                  description: male or female
                blood_type:
                  type: string
                  description: 'one of {A B O AB}'
                age:
                  type: string
                height:
                  type: string
                weight:
                  type: string
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
              required:
                - username
                - password
                - gender
                - blood_type
                - email
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
  /api/User/token/:
    post:
      summary: ''
      operationId: post-api-User-token
      responses:
        '200':
          description: OK
      description: Get JWT Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: string
        description: ''
  /api/Accelo/CreateRecord/:
    post:
      summary: ''
      operationId: post-api-Accelo-CreateRecord
      responses:
        '200':
          description: OK
#       parameters:
#         - schema:
#             type: string
#           in: header
      description: ''
      security:
        - Authorization: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ID_of_device:
                  type: string
                x:
                  type: string
                'y':
                  type: string
                z:
                  type: string
                roll:
                  type: string
                pitch:
                  type: string
                yaw:
                  type: string
                psi:
                  type: string
                theta:
                  type: string
                phi:
                  type: string
                labeled:
                  type: string
                Preprocessed:
                  type: string
                  description: '''0'' or ''1'''
              required:
                - ID_of_device
                - x
                - 'y'
                - z
  /api/Pulse/CreateRecord/:
    parameters: []
    post:
      summary: ''
      operationId: post-api-Pulse-CreateRecord
      responses:
        '200':
          description: OK
      security:
        - Authorization: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Device_ID:
                  type: string
                HeartRate:
                  type: string
                Temp:
                  type: string
                Auxiliary1:
                  type: string
                Auxiliary2:
                  type: string
                Auxiliary3:
                  type: string
                labeled:
                  type: string
                Preprocessed:
                  type: string
                  description: '''0'' or ''1'''
              required:
                - Device_ID
  /api/Devices/CreateRecord/:
    parameters: []
    post:
      summary: ''
      operationId: post-api-Devices-CreateRecord
      responses:
        '200':
          description: OK
      security:
        - Authorization: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ID_of_device:
                  type: string
                labeled:
                  type: string
                parameter1:
                  type: string
                parameter2:
                  type: string
                parameter3:
                  type: string
                parameter4:
                  type: string
                parameter5:
                  type: string
                parameter6:
                  type: string
                parameter7:
                  type: string
                parameter8:
                  type: string
                parameter9:
                  type: string
                parameter10:
                  type: string
                  description: parameter10 ........ parameter400
                parameter400:
                  type: string
                Preprocessed:
                  type: string
                  description: '''0'' or ''1'''
              required:
                - ID_of_device
      description: post devices parameters
  /api/Pulse/ViewRecords/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-Pulse-ViewRecords
      description: |
        Get items by Pulse App

  /api/Accelo/Filtered/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-api-Accelo-ViewRecords
      description: |
        filtered
      security:
        - Authorization: []

    parameters: []

  /api/Accelo/ViewRecords/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-Accelo-ViewRecord
      description: |
        Get items by Pulse App
    
    parameters: []
  /api/Devices/ViewRecords/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-devices-ViewRecords-all
      description: |
        Get items by Pulse App
     
    parameters: []

  /api/Devices/Filtered/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-api-Devices-filtered
   
      description: |
        filtered
      security:
        - Authorization: []

    parameters: []

components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: JWT Bearer token